var songs = [
    {
        songName:"Yankee Doodle",
        songQuery:"test.song.no-data",
        songArr:[
            {note: "f3Audio", sequence: 1},
            {note: "f3Audio", sequence: 2},
            {note: "g3Audio", sequence: 3},
            {note: "a3Audio", sequence: 4},
            {note: "f3Audio", sequence: 5},
            {note: "a3Audio", sequence: 6},
            {note: "g3Audio", sequence: 7},
            {note: "c3Audio", sequence: 8},
            {note: "f3Audio", sequence: 9},
            {note: "f3Audio", sequence: 10},
            {note: "g3Audio", sequence: 11},
            {note: "a3Audio", sequence: 12},
            {note: "f3Audio", sequence: 13},
            {note: "e3Audio", sequence: 14},
        ],
    },
    {
        songName:"Happy Birthday",
        songQuery:"test.song.no-data",
        songArr:[
            {note: "c3Audio", sequence: 1},
            {note: "c3Audio", sequence: 2},
            {note: "d3Audio", sequence: 3},
            {note: "c3Audio", sequence: 4},
            {note: "f3Audio", sequence: 5},
            {note: "e3Audio", sequence: 6},
            {note: "c3Audio", sequence: 7},
            {note: "c3Audio", sequence: 8},
            {note: "d3Audio", sequence: 9},
            {note: "c3Audio", sequence: 10},
            {note: "g3Audio", sequence: 11},
            {note: "f3Audio", sequence: 12},
            {note: "c3Audio", sequence: 13},
            {note: "c3Audio", sequence: 14},
            {note: "c4Audio", sequence: 14},
            {note: "c3Audio", sequence: 14},
        ],
    },
    {
        songName:"Yankee Doodle",
        songQuery:"test.song.no-data",
        songArr:[
            {note: "f3Audio", sequence: 1},
            {note: "f3Audio", sequence: 2},
            {note: "g3Audio", sequence: 3},
            {note: "a3Audio", sequence: 4},
            {note: "f3Audio", sequence: 5},
            {note: "a3Audio", sequence: 6},
            {note: "g3Audio", sequence: 7},
            {note: "c3Audio", sequence: 8},
            {note: "f3Audio", sequence: 9},
            {note: "f3Audio", sequence: 10},
            {note: "g3Audio", sequence: 11},
            {note: "a3Audio", sequence: 12},
            {note: "f3Audio", sequence: 13},
            {note: "e3Audio", sequence: 14},
        ],
    },
    {
        songName:"Yankee Doodle",
        songQuery:"test.song.no-data",
        songArr:[
            {note: "f3Audio", sequence: 1},
            {note: "f3Audio", sequence: 2},
            {note: "g3Audio", sequence: 3},
            {note: "a3Audio", sequence: 4},
            {note: "f3Audio", sequence: 5},
            {note: "a3Audio", sequence: 6},
            {note: "g3Audio", sequence: 7},
            {note: "c3Audio", sequence: 8},
            {note: "f3Audio", sequence: 9},
            {note: "f3Audio", sequence: 10},
            {note: "g3Audio", sequence: 11},
            {note: "a3Audio", sequence: 12},
            {note: "f3Audio", sequence: 13},
            {note: "e3Audio", sequence: 14},
        ],
    },
    {
        songName:"Yankee Doodle",
        songQuery:"test.song.no-data",
        songArr:[
            {note: "f3Audio", sequence: 1},
            {note: "f3Audio", sequence: 2},
            {note: "g3Audio", sequence: 3},
            {note: "a3Audio", sequence: 4},
            {note: "f3Audio", sequence: 5},
            {note: "a3Audio", sequence: 6},
            {note: "g3Audio", sequence: 7},
            {note: "c3Audio", sequence: 8},
            {note: "f3Audio", sequence: 9},
            {note: "f3Audio", sequence: 10},
            {note: "g3Audio", sequence: 11},
            {note: "a3Audio", sequence: 12},
            {note: "f3Audio", sequence: 13},
            {note: "e3Audio", sequence: 14},
        ],
    },
    {
        songName:"Yankee Doodle",
        songQuery:"test.song.no-data",
        songArr:[
            {note: "c3Audio", sequence: [8]},
            {note: "d3Audio", sequence: []},
            {note: "e3Audio", sequence: [14 ]},
            {note: "f3Audio", sequence: [1,2,5,9,10,13]},
            {note: "g3Audio", sequence: [3,7,11]},
            {note: "a3Audio", sequence: [4,6,12]},
            {note: "b3Audio", sequence: []},
            {note: "c4Audio", sequence: []},
        ],
    },
];