var songBank = [
    {
        songName:"Yankee Doodle",
        songQuery:"test.song.no-data",
        songArr:[
            {note: "f3Audio", sequence: 1},
            {note: "f3Audio", sequence: 2},
            {note: "g3Audio", sequence: 3},
            {note: "a3Audio", sequence: 4},
            {note: "f3Audio", sequence: 5},
            {note: "a3Audio", sequence: 6},
            {note: "g3Audio", sequence: 7},
            {note: "c3Audio", sequence: 8},
            {note: "f3Audio", sequence: 9},
            {note: "f3Audio", sequence: 10},
            {note: "g3Audio", sequence: 11},
            {note: "a3Audio", sequence: 12},
            {note: "f3Audio", sequence: 13},
            {note: "e3Audio", sequence: 14},
        ],
        songYoutube: "https://www.youtube.com/embed/HifEbihI2Ck?start=5"
    },
    {
        songName:"Happy Birthday",
        songQuery:"test.song.no-data",
        songArr:[
            {note: "c3Audio", sequence: 1},
            {note: "c3Audio", sequence: 2},
            {note: "d3Audio", sequence: 3},
            {note: "c3Audio", sequence: 4},
            {note: "f3Audio", sequence: 5},
            {note: "e3Audio", sequence: 6},
            {note: "c3Audio", sequence: 7},
            {note: "c3Audio", sequence: 8},
            {note: "d3Audio", sequence: 9},
            {note: "c3Audio", sequence: 10},
            {note: "g3Audio", sequence: 11},
            {note: "f3Audio", sequence: 12},
            {note: "c3Audio", sequence: 13},
            {note: "c3Audio", sequence: 14},
            {note: "c4Audio", sequence: 14},
            {note: "a3Audio", sequence: 14},
            {note: "g3Audio", sequence: 14},
            {note: "f3Audio", sequence: 14},
            {note: "e3Audio", sequence: 14},
            {note: "d3Audio", sequence: 14},
        ],
        songYoutube: "https://www.youtube.com/embed/HifEbihI2Ck?start=5"
    },
    {
        songName:"Ode To Joy",
        songQuery:"test.song.no-data",
        songArr:[
            {note: "e3Audio", sequence: 1},
            {note: "e3Audio", sequence: 2},
            {note: "f3Audio", sequence: 3},
            {note: "g3Audio", sequence: 4},
            {note: "g3Audio", sequence: 5},
            {note: "f3Audio", sequence: 6},
            {note: "e3Audio", sequence: 7},
            {note: "d3Audio", sequence: 8},
            {note: "c3Audio", sequence: 9},
            {note: "c3Audio", sequence: 10},
            {note: "d3Audio", sequence: 11},
            {note: "e3Audio", sequence: 12},
            {note: "e3Audio", sequence: 13},
            {note: "d3Audio", sequence: 14},
        ],
        songYoutube: "https://www.youtube.com/watch?v=AbXiKLA58SE"
    },
    {
        songName:"Lollipop",
        songQuery:"test.song.no-data",
        songArr:[
            {note: "d3Audio", sequence: 1},
            {note: "d3Audio", sequence: 2},
            {note: "d3Audio", sequence: 3},
            {note: "d3Audio", sequence: 4},
            {note: "e3Audio", sequence: 5},
            {note: "e3Audio", sequence: 6},
            {note: "e3Audio", sequence: 7},
            {note: "e3Audio", sequence: 8},
            {note: "f3Audio", sequence: 9},
            {note: "f3Audio", sequence: 10},
            {note: "f3Audio", sequence: 11},
            {note: "f3Audio", sequence: 12},
            {note: "g3Audio", sequence: 13},
            {note: "g3Audio", sequence: 14},
        ],
        songYoutube: "https://youtu.be/2IH8tNQAzSs"
    },
    {
        songName:"Jingle Bells",
        songQuery:"test.song.no-data",
        songArr:[
            {note: "e3Audio", sequence: 1},
            {note: "e3Audio", sequence: 2},
            {note: "e3Audio", sequence: 3},
            {note: "e3Audio", sequence: 4},
            {note: "e3Audio", sequence: 5},
            {note: "e3Audio", sequence: 6},
            {note: "e3Audio", sequence: 7},
            {note: "g3Audio", sequence: 8},
            {note: "c3Audio", sequence: 9},
            {note: "d3Audio", sequence: 10},
            {note: "e3Audio", sequence: 11},
            {note: "f3Audio", sequence: 12},
            {note: "f3Audio", sequence: 13},
            {note: "f3Audio", sequence: 14},
        ],
        songYoutube: "https://www.youtube.com/watch?v=3CWJNqyub3o"
    },
    {
        songName:"Heathens",
        songQuery:"test.song.no-data",
        songArr:[
            {note: "b3Audio", sequence: 1},
            {note: "c4Audio", sequence: 2},
            {note: "b3Audio", sequence: 3},
            {note: "g3Audio", sequence: 4},
            {note: "b3Audio", sequence: 5},
            {note: "c4Audio", sequence: 6},
            {note: "b3Audio", sequence: 7},
            {note: "g3Audio", sequence: 8},
            {note: "e3Audio", sequence: 9},
            {note: "b3Audio", sequence: 10},
            {note: "c43Audio", sequence: 11},
            {note: "b3Audio", sequence: 12},
            {note: "g3Audio", sequence: 13},
            {note: "b3Audio", sequence: 14},
        ],
        songYoutube: "https://www.youtube.com/watch?v=UprcpdwuwCg"
    },
    {
        songName:"Requiem For a Dream",
        songQuery:"test.song.no-data",
        songArr:[
            {note: "b3Audio", sequence: 1},
            {note: "a3Audio", sequence: 2},
            {note: "g3Audio", sequence: 3},
            {note: "b3Audio", sequence: 4},
            {note: "b3Audio", sequence: 5},
            {note: "b3Audio", sequence: 6},
            {note: "a3Audio", sequence: 7},
            {note: "a3Audio", sequence: 8},
            {note: "a3Audio", sequence: 9},
            {note: "g3Audio", sequence: 10},
            {note: "b3Audio", sequence: 11},
            {note: "b3Audio", sequence: 12},
            {note: "b3Audio", sequence: 13},
            {note: "a3Audio", sequence: 14},
        ],
        songYoutube: "https://www.youtube.com/watch?v=yVIRcnlRKF8"
    },
    {
        songName:"Eye of the Tiger",
        songQuery:"test.song.no-data",
        songArr:[
            {note: "c4Audio", sequence: 1},
            {note: "c4Audio", sequence: 2},
            {note: "a3Audio", sequence: 3},
            {note: "c4Audio", sequence: 4},
            {note: "c4Audio", sequence: 5},
            {note: "a3Audio", sequence: 6},
            {note: "c4Audio", sequence: 7},
            {note: "c4Audio", sequence: 8},
            {note: "f3Audio", sequence: 9},
            {note: "g3Audio", sequence: 10},
            {note: "c4Audio", sequence: 11},
            {note: "c4Audio", sequence: 12},
            {note: "a3Audio", sequence: 13},
            {note: "c4Audio", sequence: 14},
        ],
        songYoutube: "https://www.youtube.com/watch?v=btPJPFnesV4"
    },
    {
        songName:"Pink Panther Theme",
        songQuery:"test.song.no-data",
        songArr:[
            {note: "d3Audio", sequence: 1},
            {note: "e3Audio", sequence: 2},
            {note: "f3Audio", sequence: 3},
            {note: "g4Audio", sequence: 4},
            {note: "d3Audio", sequence: 5},
            {note: "e3Audio", sequence: 6},
            {note: "f3Audio", sequence: 7},
            {note: "g3Audio", sequence: 8},
            {note: "c3Audio", sequence: 9},
            {note: "b3Audio", sequence: 10},
            {note: "e3Audio", sequence: 11},
            {note: "g3Audio", sequence: 12},
            {note: "e3Audio", sequence: 13},
            {note: "d3Audio", sequence: 14},
        ],
        songYoutube: "https://www.youtube.com/watch?v=9OPc7MRm4Y8"
    },
    {
        songName:"Pirates of the Caribbean",
        songQuery:"test.song.no-data",
        songArr:[
            {note: "c3Audio", sequence: 1},
            {note: "d3Audio", sequence: 2},
            {note: "d3Audio", sequence: 3},
            {note: "d4Audio", sequence: 4},
            {note: "e3Audio", sequence: 5},
            {note: "f3Audio", sequence: 6},
            {note: "f3Audio", sequence: 7},
            {note: "f3Audio", sequence: 8},
            {note: "g3Audio", sequence: 9},
            {note: "e3Audio", sequence: 10},
            {note: "e3Audio", sequence: 11},
            {note: "d3Audio", sequence: 12},
            {note: "c3Audio", sequence: 13},
            {note: "d3Audio", sequence: 14},
        ],
        songYoutube: "https://www.youtube.com/watch?v=K3pU67zxPOM"
    },
    {
        songName:"In The End",
        songQuery:"test.song.no-data",
        songArr:[
            {note: "d3Audio", sequence: 1},
            {note: "a3Audio", sequence: 2},
            {note: "a3Audio", sequence: 3},
            {note: "f4Audio", sequence: 4},
            {note: "e3Audio", sequence: 5},
            {note: "e3Audio", sequence: 6},
            {note: "e3Audio", sequence: 7},
            {note: "e3Audio", sequence: 8},
            {note: "f3Audio", sequence: 9},
            {note: "d3Audio", sequence: 10},
            {note: "a3Audio", sequence: 11},
            {note: "a3Audio", sequence: 12},
            {note: "f3Audio", sequence: 13},
            {note: "e3Audio", sequence: 14},
        ],
        songYoutube: "https://www.youtube.com/watch?v=eVTXPUF4Oz4"
    }
];